name: Publish to TestFlight
description: Uploads an IPA file to TestFlight using App Store Connect API.

inputs:
    file:
        description: The path to the IPA file to be uploaded to TestFlight.
        required: true
    api-key:
        description: The base64-encoded App Store Connect API private key (.p8 file).
        required: true
    api-key-id:
        description: The App Store Connect API Key ID.
        required: true
    api-issuer-id:
        description: The App Store Connect API Issuer ID.
        required: true

runs:
    using: composite
    steps:
        - name: 🚀 Upload to TestFlight
          shell: bash
          env:
              FILE: ${{ inputs.file }}
              API_KEY: ${{ inputs.api-key }}
              API_KEY_ID: ${{ inputs.api-key-id }}
              API_ISSUER_ID: ${{ inputs.api-issuer-id }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/upload_testflight.sh"
              "${{ github.action_path }}/scripts/upload_testflight.sh"
