name: Test Godot
description: Test a Godot project by building C# code and importing assets.

inputs:
    project:
        description: Path to the Godot project folder containing the project.godot file
        required: true
    global-json-file:
        description: Path to global.json which specifies the Godot version for the build
        required: true

runs:
    using: composite
    steps:
        - name: 🧪 Test Project
          shell: bash
          env:
              PROJECT_DIR: ${{ inputs.project }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/test_project.sh"
              "${{ github.action_path }}/scripts/test_project.sh"
