name: Test Godot
description: Test a Godot project by building C# code and importing assets.

inputs:
    project:
        description: Path to the Godot project folder containing the project.godot file
        required: true
    godot-path:
        description: Path to Godot executable (default $HOME/.godot/Godot_v{VERSION}.app/Contents/MacOS/Godot on macOS or $HOME/.godot/Godot_v{VERSION} on Linux)
        required: false
        default: ""

runs:
    using: composite
    steps:
        - name: 🧪 Test Project
          shell: bash
          env:
              PROJECT_DIR: ${{ inputs.project }}
              GODOT_PATH: ${{ inputs.godot-path }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/test_project.sh"
              "${{ github.action_path }}/scripts/test_project.sh"
