name: Nuget Release
description: Uploads NuGet package to nuget.org.

inputs:
  name:
    description: The name of the NuGet package.
    required: true
  api-key:
    description: NuGet API key used for authenticating and publishing the package.
    required: true

runs:
  using: composite
  steps:
    - name: 🚀 Publish NuGet Package
      shell: bash
      run: dotnet nuget push ./artifacts/${{ inputs.name }}.nupkg --api-key ${{ inputs.api-key }} --skip-duplicate --source https://api.nuget.org/v3/index.json
