name: Select Xcode
description: Validates and selects the appropriate Xcode version with iOS SDK compatibility.

inputs:
  min-ios-sdk-version:
    description: "Minimum iOS SDK version required (e.g., 18.0)"
    required: true
  min-xcode-version:
    description: "Minimum Xcode version required (e.g., 16.0)"
    required: true

outputs:
  xcode-version:
    description: "Selected Xcode version"
    value: ${{ steps.select_xcode.outputs.xcode-version }}
  ios-sdk-version:
    description: "Selected iOS SDK version"
    value: ${{ steps.select_xcode.outputs.ios-sdk-version }}
  xcode-path:
    description: "Path to the selected Xcode installation"
    value: ${{ steps.select_xcode.outputs.xcode-path }}
  switched:
    description: "Whether Xcode was switched (true/false)"
    value: ${{ steps.select_xcode.outputs.switched }}
  previous-sdk:
    description: "Previous iOS SDK version before switching"
    value: ${{ steps.select_xcode.outputs.previous-sdk }}

runs:
  using: composite
  steps:
    - name: 🎯 Select Xcode
      id: select_xcode
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/select_xcode.sh"
        "${{ github.action_path }}/scripts/select_xcode.sh" \
        "${{ inputs.min-ios-sdk-version }}" \
        "${{ inputs.min-xcode-version }}"
