name: Format Files
description: Format various file types using Prettier including YAML, JSON, Markdown, CSS, HTML, JavaScript, TypeScript, and Shell scripts.

inputs:
    files:
        description: File patterns to format such as **/*.{yml,yaml,json,md,js,ts,css,html,sh}
        required: true
    ignore-path:
        description: Path to ignore file for excluding files from formatting
        required: false
        default: ""

runs:
    using: composite
    steps:
        - name: 🔧 Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: "20"

        - name: 📦 Install Prettier and Plugins
          shell: bash
          run: |
              npm init -y
              npm install prettier@latest prettier-plugin-sh@latest
              echo "Installed packages:"
              npm list prettier prettier-plugin-sh

        - name: 🎨 Format Files
          shell: bash
          env:
              FILES_PATTERN: ${{ inputs.files }}
              IGNORE_PATH: ${{ inputs.ignore-path }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/format_files.sh"
              "${{ github.action_path }}/scripts/format_files.sh"
