name: Download Artifact
description: Download a build artifact and restore original paths using metadata.

inputs:
    name:
        description: Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
        required: false
    artifact-ids:
        description: IDs of the artifacts to download, comma-separated. Either inputs `artifact-ids` or `name` can be used, but not both.
        required: false
    path:
        description: Destination path. Supports basic tilde expansion. If not specified with metadata, files will be restored to their original paths.
        required: false
    pattern:
        description: A glob pattern to the artifacts that should be downloaded. Ignored if name is specified.
        required: false
    merge-multiple:
        description: When multiple artifacts are matched, this changes the behavior of the destination directories. If true, the downloaded artifacts will be in the same directory specified by path. If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
        required: false
        default: "false"
    github-token:
        description: The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run.
        required: false
        default: ${{ github.token }}
    repository:
        description: The repository owner and the repository name joined together by "/". If github-token is specified, this is the repository that artifacts will be downloaded from.
        required: false
        default: ${{ github.repository }}
    run-id:
        description: The id of the workflow run where the desired download artifact was uploaded from. If github-token is specified, this is the run that artifacts will be downloaded from.
        required: false
        default: ${{ github.run_id }}

outputs:
    download-path:
        description: Path of artifact download
        value: ${{ steps.restore.outputs.download-path }}

runs:
    using: composite
    steps:
        - name: 📥 Download Artifact
          id: download
          uses: actions/download-artifact@v4
          with:
              name: ${{ inputs.name }}
              artifact-ids: ${{ inputs.artifact-ids }}
              path: ${{ inputs.path || format('.artifact-download-{0}', inputs.name || 'all') }}
              pattern: ${{ inputs.pattern }}
              merge-multiple: ${{ inputs.merge-multiple }}
              github-token: ${{ inputs.github-token }}
              repository: ${{ inputs.repository }}
              run-id: ${{ inputs.run-id }}

        - name: 📦 Restore Artifact Paths
          id: restore
          shell: bash
          env:
              ARTIFACT_NAME: ${{ inputs.name || 'all' }}
              DESTINATION_PATH: ${{ inputs.path }}
              DOWNLOAD_PATH: ${{ steps.download.outputs.download-path }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/download_artifact.sh"
              "${{ github.action_path }}/scripts/download_artifact.sh"
