name: Download Artifact
description: Download a build artifact that was previously uploaded

inputs:
    name:
        description: Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
        required: false
    path:
        description: |
            Destination path. Supports basic tilde expansion.
            If empty and artifact has metadata, files are restored to their original paths.
            Defaults to $GITHUB_WORKSPACE.
        required: false
    pattern:
        description: |
            A glob pattern to the artifacts that should be downloaded.
            Ignored if name is specified.
        required: false
    merge-multiple:
        description: |
            When multiple artifacts are matched, this changes the behavior of the destination directories.
            If true, the downloaded artifacts will be in the same directory specified by path.
            If false, the downloaded artifacts will be extracted into individual named directories within the specified path.
        required: false
        default: "false"
    github-token:
        description: The GitHub token used to authenticate with the GitHub API. This is required when downloading artifacts from a different repository or from a different workflow run.
        required: false
        default: ${{ github.token }}
    repository:
        description: The repository owner and name. For example, actions/checkout. Defaults to the current repository.
        required: false
        default: ${{ github.repository }}
    run-id:
        description: The id of the workflow run where the desired download artifact was uploaded from. Defaults to the current run id.
        required: false
        default: ${{ github.run_id }}

outputs:
    download-path:
        description: Absolute path where the artifact(s) were downloaded
        value: ${{ steps.restore.outputs.download-path }}

runs:
    using: composite
    steps:
        - name: Download Artifact
          id: download
          uses: actions/download-artifact@v4
          with:
              name: ${{ inputs.name }}
              path: ${{ inputs.path || format('.artifact-download-{0}', inputs.name || 'temp') }}
              pattern: ${{ inputs.pattern }}
              merge-multiple: ${{ inputs.merge-multiple }}
              github-token: ${{ inputs.github-token }}
              repository: ${{ inputs.repository }}
              run-id: ${{ inputs.run-id }}

        - name: Restore Original Paths
          id: restore
          shell: bash
          env:
              ARTIFACT_NAME: ${{ inputs.name }}
              DOWNLOAD_PATH: ${{ inputs.path }}
              DOWNLOADED_TO: ${{ steps.download.outputs.download-path }}
              PATTERN: ${{ inputs.pattern }}
              MERGE_MULTIPLE: ${{ inputs.merge-multiple }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/download_artifact.sh"
              "${{ github.action_path }}/scripts/download_artifact.sh"
