name: Pack Godot Addon
description: Package a Godot addon into a zip file with automatic version management.

inputs:
    addon:
        description: Path to the Godot addon directory such as addons/my-addon
        required: true
    version:
        description: Version number to apply to the addon
        required: true
    filename:
        description: Name of the output addon file without .zip extension
        required: true
    readme:
        description: Path to the README file to include
        required: false
        default: ""
    license:
        description: Path to the LICENSE file to include
        required: false
        default: ""

outputs:
    package:
        description: Path to the created addon zip file
        value: ${{ steps.pack.outputs.package }}
    modified-files:
        description: Path to modified plugin.cfg file in workspace
        value: ${{ steps.pack.outputs.modified-files }}

runs:
    using: composite
    steps:
        - name: 📦 Pack Godot Addon
          id: pack
          shell: bash
          env:
              ADDON_PATH: ${{ inputs.addon }}
              ADDON_VERSION: ${{ inputs.version }}
              ADDON_FILENAME: ${{ inputs.filename }}
              ADDON_README: ${{ inputs.readme }}
              ADDON_LICENSE: ${{ inputs.readme }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/pack_addon.sh"
              "${{ github.action_path }}/scripts/pack_addon.sh"
