name: Pack Unity Package
description: Package a Unity package as a local tarball with automatic version management.

inputs:
    package:
        description: Path to the Unity package directory such as Packages/com.example.package
        required: true
    version:
        description: Version number to apply to the package
        required: true
    filename:
        description: Name of the output package file without .tgz extension
        required: true

outputs:
    package:
        description: Path to the created package tarball file
        value: ${{ steps.pack.outputs.package }}
    modified-files:
        description: Path to modified package.json file in workspace
        value: ${{ steps.pack.outputs.modified-files }}

runs:
    using: composite
    steps:
        - name: 📦 Pack Unity Package
          id: pack
          shell: bash
          env:
              PACKAGE_PATH: ${{ inputs.package }}
              PACKAGE_VERSION: ${{ inputs.version }}
              PACKAGE_FILENAME: ${{ inputs.filename }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/pack_package.sh"
              "${{ github.action_path }}/scripts/pack_package.sh"
