name: Format Shell
description: Formats shell scripts using shfmt.

inputs:
    path:
        description: "Path to search for shell scripts"
        required: false
        default: "."
    exclude-paths:
        description: "Comma-separated paths to exclude"
        required: false
        default: "./sandbox"

runs:
    using: composite
    steps:
        - name: 🔧 Install shfmt
          shell: bash
          run: |
              if ! command -v shfmt &> /dev/null; then
                  echo "Installing shfmt..."

                  LATEST_URL=$(curl -s https://api.github.com/repos/mvdan/sh/releases/latest | grep "browser_download_url.*linux_amd64" | cut -d '"' -f 4)

                  if [ -z "$LATEST_URL" ]; then
                      echo "Error: Failed to get latest release URL from GitHub API"
                      exit 1
                  fi

                  echo "Downloading shfmt from: $LATEST_URL"
                  curl -L -o shfmt "$LATEST_URL"
                  chmod +x shfmt
                  sudo mv shfmt /usr/local/bin/
                  echo "shfmt installed successfully"
              else
                  echo "shfmt is already installed"
              fi

        - name: 🎨 Format Shell Scripts
          shell: bash
          run: |
              chmod +x "${{ github.action_path }}/scripts/format_shell.sh"
              "${{ github.action_path }}/scripts/format_shell.sh" "${{ inputs.path }}" "${{ inputs.exclude-paths }}"
