name: Format Shell
description: Formats shell scripts using shfmt.

inputs:
    path:
        description: "Path to search for shell scripts"
        required: false
        default: "."
    exclude-paths:
        description: "Comma-separated paths to exclude"
        required: false
        default: "./sandbox"

runs:
    using: composite
    steps:
        - name: 🔧 Setup Node.js
          uses: actions/setup-node@v4
          with:
              node-version: "20"

        - name: 🔧 Install shfmt
          shell: bash
          run: |
              if ! command -v shfmt &> /dev/null; then
                  echo "Installing shfmt via npm..."
                  npm install -g shfmt

                  export PATH="$(npm prefix -g)/bin:$PATH"
                  echo "$(npm prefix -g)/bin" >> $GITHUB_PATH

                  if command -v shfmt &> /dev/null; then
                      echo "shfmt installed successfully at: $(which shfmt)"
                      shfmt --version
                  else
                      echo "shfmt installation failed or not in PATH"
                      echo "Checking npm global bin directory:"
                      ls -la "$(npm prefix -g)/bin/"
                      exit 1
                  fi
              else
                  echo "shfmt is already installed at: $(which shfmt)"
              fi

        - name: 🎨 Format Shell Scripts
          shell: bash
          run: |
              chmod +x "${{ github.action_path }}/scripts/format_shell.sh"
              "${{ github.action_path }}/scripts/format_shell.sh" "${{ inputs.path }}" "${{ inputs.exclude-paths }}"
