name: Nuget Pack
description: Packages a .NET project and uploads the NuGet artifact.

inputs:
  project:
    description: Path to the .NET project (.csproj) file, relative to the repository root.
    required: true
  version:
    description: Version number to apply to the package.
    required: true
  configuration:
    description: Build configuration (e.g., Release or Debug) for the package.
    required: true
  name:
    description: Desired name for the uploaded NuGet package artifact.
    required: true
  duration:
    description: Retention duration (in days) for the uploaded artifact. A value of 0 uses the default retention period.
    required: false
    default: "1"

runs:
  using: composite
  steps:
    - name: 📦 Pack NuGet Package
      shell: bash
      run: dotnet pack --no-build --configuration ${{ inputs.configuration }} /p:PackageVersion=${{ inputs.version }} ${{ inputs.project }}

    - name: 🚚 Move NuGet Package
      shell: bash
      run: |
        mkdir -p ./artifacts
        mv $(find . -name "*.nupkg") ./artifacts/${{ inputs.name }}.nupkg

    - name: 📤 Upload NuGet Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ./artifacts/${{ inputs.name }}.nupkg
        retention-days: ${{ inputs.duration }}
