name: Bump Version
description: Calculates and bumps the next version based on the latest Git tag.

inputs:
    version-type:
        description: Type of version bump such as major, minor, or patch.
        required: true

outputs:
    latest-version:
        description: The latest version derived from the latest Git tag.
        value: ${{ steps.bump-version.outputs.latest-version }}
    next-version:
        description: The calculated next version based on the latest version.
        value: ${{ steps.bump-version.outputs.next-version }}

runs:
    using: composite
    steps:
        - name: 🔖 Bump Version
          id: bump-version
          shell: bash
          env:
              VERSION_TYPE: ${{ inputs.version-type }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/bump_version.sh"
              "${{ github.action_path }}/scripts/bump_version.sh"
