name: Bump Version
description: Calculates and bumps the next version based on the latest Git tag.

inputs:
  version-type:
    description: Type of version bump (major, minor, patch).
    required: true

outputs:
  latest-version:
    description: The latest version, derived from the latest Git tag.
    value: ${{ steps.fetch_version.outputs.latest_version }}
  next-version:
    description: The calculated next version based on the latest version.
    value: ${{ steps.bump_version.outputs.next_version }}

runs:
  using: composite
  steps:
    - name: 🔖 Fetch Version
      shell: bash
      id: fetch_version
      run: |
        git fetch --tags
        latest_version=$(git tag --sort=-v:refname | head -n 1)

        if [ -z "$latest_version" ]; then
          latest_version="0.0.0"
        fi

        echo latest_version=$latest_version >> $GITHUB_OUTPUT

    - name: 🧮 Bump Version
      shell: bash
      id: bump_version
      run: |
        IFS=. read -r major minor patch <<< "${{ steps.fetch_version.outputs.latest_version }}"

        case "${{ inputs.version-type }}" in
          major) major=$((major + 1)); minor=0; patch=0 ;;
          minor) minor=$((minor + 1)); patch=0 ;;
          patch) patch=$((patch + 1)) ;;
        esac

        next_version="$major.$minor.$patch"
        echo next_version=$next_version >> $GITHUB_OUTPUT
