name: Format .NET
description: Formats a .NET project.

inputs:
    project:
        description: The relative path to the .NET project (.csproj) or solution (.sln) file.
        required: true

runs:
    using: composite
    steps:
        - name: 🔍 Format Project
          shell: bash
          run: |
              chmod +x "${{ github.action_path }}/scripts/format_project.sh"
              "${{ github.action_path }}/scripts/format_project.sh" "${{ inputs.project }}"
