name: Format .NET
description: Formats a .NET project.

inputs:
  project:
    description: The relative path to the .NET project (.csproj) file.
    required: true

runs:
  using: composite
  steps:
    - name: 🛠️ Setup .NET SDK
      uses: actions/setup-dotnet@v4
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true
      with:
        global-json-file: ${{ inputs.global-json-file }}

    - name: 🔍 Format Project
      shell: bash
      run: dotnet format --verify-no-changes ${{ inputs.project }}
