name: Setup Unity
description: Download, install, and cache Unity for macOS and Linux platforms with iOS and Android support.

inputs:
    project:
        description: Path to the Unity project directory
        required: false
        default: "."
    unity-version:
        description: Unity version to install with revision such as 6000.1.9f1 (ed7b183fd33d)
        required: false
        default: ""
    unity-modules:
        description: Comma-separated list of target modules to install such as ios, android
        required: false
        default: ""
    unity-path:
        description: Custom directory for Unity installations (default /Applications/Unity on macOS, $HOME on Linux)
        required: false
        default: ""

outputs:
    unity-path:
        description: Root directory of Unity installation
        value: ${{ steps.install-unity.outputs.unity-path }}
    unity-version:
        description: Installed Unity version
        value: ${{ steps.get-unity-info.outputs.version }}

runs:
    using: composite
    steps:
        - name: ✅ Validate Platform Support
          shell: bash
          run: |
              if [[ "${RUNNER_OS}" != "macOS" && "${RUNNER_OS}" != "Linux" ]]; then
                echo "::error::This action only supports macOS and Linux. Unsupported platform: ${RUNNER_OS}"
                exit 1
              fi
              echo "::notice::Platform validation passed for ${RUNNER_OS}"

        - name: 📖 Get Unity Info
          id: get-unity-info
          shell: bash
          env:
              PROJECT_PATH: ${{ inputs.project }}
              UNITY_VERSION_INPUT: ${{ inputs.unity-version }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/get_unity_info.sh"
              "${{ github.action_path }}/scripts/get_unity_info.sh"

        - name: 🔧 Prepare Download Directory
          id: prepare-paths
          shell: bash
          env:
              UNITY_VERSION: ${{ steps.get-unity-info.outputs.version }}
          run: |
              DOWNLOAD_DIR="${RUNNER_TEMP}/.downloads/unity/${UNITY_VERSION}"
              echo "download-dir=${DOWNLOAD_DIR}" >> "${GITHUB_OUTPUT}"
              echo "::notice::Download directory: ${DOWNLOAD_DIR}"

        - name: ⬇️ Download Unity
          shell: bash
          env:
              UNITY_VERSION: ${{ steps.get-unity-info.outputs.version }}
              UNITY_CHANGESET: ${{ steps.get-unity-info.outputs.changeset }}
              UNITY_MODULES: ${{ inputs.unity-modules }}
              DOWNLOAD_DIR: ${{ steps.prepare-paths.outputs.download-dir }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/download_unity.sh"
              "${{ github.action_path }}/scripts/download_unity.sh"

        - name: ⚙️ Install Unity
          id: install-unity
          shell: bash
          env:
              UNITY_VERSION: ${{ steps.get-unity-info.outputs.version }}
              UNITY_MODULES: ${{ inputs.unity-modules }}
              UNITY_PATH: ${{ inputs.unity-path }}
              DOWNLOAD_DIR: ${{ steps.prepare-paths.outputs.download-dir }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/install_unity.sh"
              "${{ github.action_path }}/scripts/install_unity.sh"

        - name: 📱 Configure Android Tools
          if: contains(inputs.unity-modules, 'android')
          shell: bash
          env:
              UNITY_VERSION: ${{ steps.get-unity-info.outputs.version }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/install_android_tools.sh"
              "${{ github.action_path }}/scripts/install_android_tools.sh"
