name: Setup Unity
description: Downloads, installs, and caches Unity for the specified platform.
inputs:
  unity-version:
    description: The Unity version to install with revision (e.g., "6000.1.9f1 (ed7b183fd33d)").
    required: false
  unity-modules:
    description: Comma-separated list of target modules to install (e.g., "ios,android,webgl").
    required: false
    default: ""
  cache:
    description: Whether to use caching for the downloaded installers.
    required: false
    default: "true"
  project-path:
    description: Path to the Unity project directory.
    required: false
    default: "."
outputs:
  download-cache-hit:
    description: "A boolean value to indicate if the download cache was hit."
    value: ${{ steps.cache_downloads.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: 📖 Get Unity Info
      id: get_unity_info
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/get_unity_info.sh"
        "${{ github.action_path }}/scripts/get_unity_info.sh" "${{ inputs.project-path }}" "${{ inputs.unity-version }}"
    - name: 🔧 Prepare Paths and Module ID
      id: prepare_paths
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/get_modules_id.sh"
        VERSION="${{ steps.get_unity_info.outputs.version }}"
        MODULES_ID=$("${{ github.action_path }}/scripts/get_modules_id.sh" "${{ inputs.unity-modules }}")
        DOWNLOAD_DIR="$HOME/.unity/${VERSION}"
        echo "download_dir=${DOWNLOAD_DIR}" >> $GITHUB_OUTPUT
        echo "cache_key=unity-download-${VERSION}-${RUNNER_OS}-${MODULES_ID}" >> $GITHUB_OUTPUT
    - name: 💾 Cache Downloaded Installers
      id: cache_downloads
      if: inputs.cache == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ steps.prepare_paths.outputs.download_dir }}
        key: ${{ steps.prepare_paths.outputs.cache_key }}
    - name: ⬇️ Download Unity
      if: steps.cache_downloads.outputs.cache-hit != 'true' || inputs.cache != 'true'
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/download_unity.sh"
        "${{ github.action_path }}/scripts/download_unity.sh" \
        "${{ steps.get_unity_info.outputs.version }}" \
        "${{ steps.get_unity_info.outputs.revision }}" \
        "${{ inputs.unity-modules }}" \
        "${{ steps.prepare_paths.outputs.download_dir }}"
    - name: ⚙️ Install Unity
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/install_unity.sh"
        "${{ github.action_path }}/scripts/install_unity.sh" \
        "${{ steps.get_unity_info.outputs.version }}" \
        "${{ inputs.unity-modules }}" \
        "${{ steps.prepare_paths.outputs.download_dir }}"
    - name: 🔧 Configure Environment
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/configure_environment.sh"
        "${{ github.action_path }}/scripts/configure_environment.sh" "${{ steps.get_unity_info.outputs.version }}"