name: Setup Unity
description: Downloads, installs, and caches Unity for macOS, Linux, and Windows platforms.
inputs:
  unity-version:
    description: The Unity version to install with revision (e.g., "6000.1.9f1 (ed7b183fd33d)").
    required: false
  unity-modules:
    description: Comma-separated list of target modules to install (e.g., "ios,android,webgl").
    required: false
    default: ""
  cache:
    description: Whether to use caching for the downloaded installers.
    required: false
    default: "true"
  project-path:
    description: Path to the Unity project directory.
    required: false
    default: "."
  unity-username:
    description: "Your Unity account email address."
    required: false
  unity-password:
    description: "Your Unity account password."
    required: false
  unity-serial:
    description: "Your Unity license serial key (Pro/Plus)."
    required: false
outputs:
  download-cache-hit:
    description: "A boolean value to indicate if the download cache was hit."
    value: ${{ steps.cache_downloads.outputs.cache-hit }}
  unity-path:
    description: "The path to the Unity executable."
    value: ${{ steps.install_unity.outputs.unity_path }}
runs:
  using: composite
  steps:
    - name: ✅ Validate Platform Support
      shell: bash
      run: |
        if [[ "$RUNNER_OS" != "macOS" && "$RUNNER_OS" != "Linux" && "$RUNNER_OS" != "Windows" ]]; then
          echo "::error::This action supports macOS, Linux, and Windows. Unsupported platform: $RUNNER_OS"
          exit 1
        fi
        echo "::notice::Platform validation passed for $RUNNER_OS"

    - name: 📖 Get Unity Info
      id: get_unity_info
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/get_unity_info.sh"
        "${{ github.action_path }}/scripts/get_unity_info.sh" "${{ inputs.project-path }}" "${{ inputs.unity-version }}"

    - name: 🔧 Prepare Paths and Module ID
      id: prepare_paths
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/get_modules_id.sh"
        VERSION="${{ steps.get_unity_info.outputs.version }}"
        MODULES_ID=$("${{ github.action_path }}/scripts/get_modules_id.sh" "${{ inputs.unity-modules }}")
        DOWNLOAD_DIR="$HOME/.unity/${VERSION}"

        case "$RUNNER_OS" in
          "macOS")
            ARCH="arm64"
            ;;
          "Linux")
            ARCH="x64"
            ;;
          "Windows")
            ARCH="x64"
            ;;
          *)
            ARCH="unknown"
            ;;
        esac

        echo "download_dir=${DOWNLOAD_DIR}" >> $GITHUB_OUTPUT
        echo "cache_key=unity-download-${VERSION}-${RUNNER_OS}-${ARCH}-${MODULES_ID}" >> $GITHUB_OUTPUT
        echo "::notice::Download directory: ${DOWNLOAD_DIR}"
        echo "::notice::Cache key: unity-download-${VERSION}-${RUNNER_OS}-${ARCH}-${MODULES_ID}"

    - name: 💾 Cache Downloaded Installers
      id: cache_downloads
      if: inputs.cache == 'true'
      uses: actions/cache@v4
      with:
        path: ${{ steps.prepare_paths.outputs.download_dir }}
        key: ${{ steps.prepare_paths.outputs.cache_key }}

    - name: ⬇️ Download Unity
      if: steps.cache_downloads.outputs.cache-hit != 'true' || inputs.cache != 'true'
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/download_unity.sh"
        "${{ github.action_path }}/scripts/download_unity.sh" \
        "${{ steps.get_unity_info.outputs.version }}" \
        "${{ steps.get_unity_info.outputs.changeset }}" \
        "${{ inputs.unity-modules }}" \
        "${{ steps.prepare_paths.outputs.download_dir }}"

    - name: ⚙️ Install Unity
      id: install_unity
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/install_unity.sh"
        "${{ github.action_path }}/scripts/install_unity.sh" \
        "${{ steps.get_unity_info.outputs.version }}" \
        "${{ inputs.unity-modules }}" \
        "${{ steps.prepare_paths.outputs.download_dir }}"

    - name: 🔑 Activate Unity License
      if: inputs.unity-username != '' && inputs.unity-password != '' && inputs.unity-serial != ''
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/activate_unity.sh"
        "${{ github.action_path }}/scripts/activate_unity.sh" \
          "${{ inputs.unity-username }}" \
          "${{ inputs.unity-password }}" \
          "${{ inputs.unity-serial }}"
