name: Setup Godot
description: Downloads, installs, and caches Godot for the specified platform.

inputs:
  global-json-file:
    description: Path to the `global.json` file to extract the Godot version.
    required: true
  path:
    description: Path to the installation directory for Godot.
    required: true

runs:
  using: composite
  steps:
    - name: ðŸ“– Read Godot version
      id: read_version
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/read_version.sh"
        version=$("${{ github.action_path }}/scripts/read_version.sh" "${{ inputs.global-json-file }}")
        echo version="$version" >> "$GITHUB_OUTPUT"

    - name: ðŸ’¾ Restore Cache Godot
      id: cache_godot
      uses: actions/cache/restore@v4
      with:
        key: godot-${{ steps.read_version.outputs.version }}-${{ runner.os }}
        path: ${{ inputs.path }}

    - name: â¬‡ï¸ Download Godot
      id: download_godot
      if: steps.cache_godot.outputs.cache-hit != 'true'
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/download_godot.sh"
        "${{ github.action_path }}/scripts/download_godot.sh" "${{ steps.read_version.outputs.version }}" "${{ inputs.path }}" "${{ runner.os }}"

    - name: ðŸ’¾ Save Cache Godot
      if: steps.cache_godot.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache_godot.outputs.cache-primary-key }}
        path: ${{ inputs.path }}

    - name: âš™ï¸ Install Godot
      id: install_godot
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/install_godot.sh"
        executable_file=$("${{ github.action_path }}/scripts/install_godot.sh" "${{ steps.read_version.outputs.version }}" "${{ inputs.path }}" "${{ runner.os }}")
        echo GODOT="$executable_file" >> "$GITHUB_ENV"
