name: Setup Godot
description: Download, install, and cache Godot editor and export templates for specified platforms.

inputs:
    global-json-file:
        description: Path to the global.json file to extract the Godot version and stage
        required: true
    target-platforms:
        description: Comma-separated list of target platforms for export templates such as iOS, Android, macOS, Linux, Windows
        required: false
        default: ""
    godot-path:
        description: Custom directory for Godot installation (default $HOME/.godot)
        required: false
        default: ""

outputs:
    godot-path:
        description: Directory containing Godot installation
        value: ${{ steps.install-editor.outputs.godot-path }}
    godot-version:
        description: Installed Godot version
        value: ${{ steps.get-godot-info.outputs.version }}

runs:
    using: composite
    steps:
        - name: 📖 Get Godot Info
          id: get-godot-info
          shell: bash
          env:
              GLOBAL_JSON_FILE: ${{ inputs.global-json-file }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/get_godot_info.sh"
              "${{ github.action_path }}/scripts/get_godot_info.sh"

        - name: 🔧 Prepare Download Directory
          id: prepare-paths
          shell: bash
          env:
              GODOT_VERSION: ${{ steps.get-godot-info.outputs.version }}
              GODOT_STAGE: ${{ steps.get-godot-info.outputs.stage }}
          run: |
              DOWNLOAD_DIR="${RUNNER_TEMP}/.downloads/godot/${GODOT_VERSION}-${GODOT_STAGE}"
              echo "download-dir=${DOWNLOAD_DIR}" >> "${GITHUB_OUTPUT}"
              echo "::notice::Download directory: ${DOWNLOAD_DIR}"

        - name: ⬇️ Download Editor
          shell: bash
          env:
              GODOT_VERSION: ${{ steps.get-godot-info.outputs.version }}
              GODOT_STAGE: ${{ steps.get-godot-info.outputs.stage }}
              GODOT_PATH: ${{ inputs.godot-path }}
              DOWNLOAD_DIR: ${{ steps.prepare-paths.outputs.download-dir }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/download_editor.sh"
              "${{ github.action_path }}/scripts/download_editor.sh"

        - name: 📂 Get Templates Directory
          id: get-templates-dir
          if: inputs.target-platforms != ''
          shell: bash
          run: |
              chmod +x "${{ github.action_path }}/scripts/get_templates_dir.sh"
              "${{ github.action_path }}/scripts/get_templates_dir.sh"

        - name: ⬇️ Download Templates
          if: inputs.target-platforms != ''
          shell: bash
          env:
              GODOT_VERSION: ${{ steps.get-godot-info.outputs.version }}
              GODOT_STAGE: ${{ steps.get-godot-info.outputs.stage }}
              TEMPLATES_DIR: ${{ steps.get-templates-dir.outputs.templates-dir }}
              TARGET_PLATFORMS: ${{ inputs.target-platforms }}
              DOWNLOAD_DIR: ${{ steps.prepare-paths.outputs.download-dir }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/download_templates.sh"
              "${{ github.action_path }}/scripts/download_templates.sh"

        - name: ⚙️ Install Editor
          id: install-editor
          shell: bash
          env:
              GODOT_VERSION: ${{ steps.get-godot-info.outputs.version }}
              GODOT_STAGE: ${{ steps.get-godot-info.outputs.stage }}
              GODOT_PATH: ${{ inputs.godot-path }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/install_editor.sh"
              "${{ github.action_path }}/scripts/install_editor.sh"
