name: Setup Godot
description: Downloads, installs, and caches Godot for the specified platform.

inputs:
  global-json-file:
    description: Path to the `global.json` file to extract the Godot version.
    required: true

runs:
  using: composite
  steps:
    - name: 📖 Read Godot version
      id: read_version
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/read_version.sh"
        version=$("${{ github.action_path }}/scripts/read_version.sh" "${{ inputs.global-json-file }}")
        echo version="$version" >> "$GITHUB_OUTPUT"

    - name: 💾 Restore Cache Editor
      id: cache_editor
      uses: actions/cache/restore@v4
      with:
        key: godot-editor-${{ steps.read_version.outputs.version }}-${{ runner.os }}
        path: ~/.godot

    - name: ⬇️ Download Editor
      if: steps.cache_editor.outputs.cache-hit != 'true'
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/download_editor.sh"
        "${{ github.action_path }}/scripts/download_editor.sh" "${{ steps.read_version.outputs.version }}" "${{ runner.os }}"

    - name: 💾 Save Cache Editor
      if: steps.cache_editor.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache_editor.outputs.cache-primary-key }}
        path: ~/.godot

    - name: 📂 Get Templates Directory
      id: get_templates_dir
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/get_templates_dir.sh"
        templates_dir=$("${{ github.action_path }}/scripts/get_templates_dir.sh" "${{ runner.os }}")
        echo templates_dir=${templates_dir} >> "$GITHUB_OUTPUT"

    - name: 💾 Restore Cache Templates
      id: cache_templates
      uses: actions/cache/restore@v4
      with:
        key: godot-templates-${{ steps.read_version.outputs.version }}
        path: ${{ steps.get_templates_dir.outputs.templates_dir }}

    - name: ⬇️ Download Templates
      if: steps.cache_templates.outputs.cache-hit != 'true'
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/download_templates.sh"
        "${{ github.action_path }}/scripts/download_templates.sh" "${{ steps.read_version.outputs.version }}" "${{ steps.get_templates_dir.outputs.templates_dir }}"

    - name: 💾 Save Cache Templates
      if: steps.cache_templates.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache_templates.outputs.cache-primary-key }}
        path: ${{ steps.get_templates_dir.outputs.templates_dir }}

    - name: ⚙️ Install Editor
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/install_editor.sh"
        executable_file=$("${{ github.action_path }}/scripts/install_editor.sh" "${{ steps.read_version.outputs.version }}" "${{ runner.os }}")
        echo GODOT="$executable_file" >> "$GITHUB_ENV"
