name: Setup Godot
description: Downloads, installs, and caches Godot for the specified platform.

inputs:
  global-json-file:
    description: Path to the `global.json` file to extract the Godot version.
    required: true

runs:
  using: composite
  steps:
    - name: ðŸ“– Read Godot version
      id: read_version
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/read_version.sh"
        version=$("${{ github.action_path }}/scripts/read_version.sh" "${{ inputs.global-json-file }}")
        echo version="$version" >> "$GITHUB_OUTPUT"

    - name: ðŸ’¾ Restore Cache Editor
      id: cache_editor
      uses: actions/cache/restore@v4
      with:
        key: godot-${{ steps.read_version.outputs.version }}-${{ runner.os }}
        path: ~/.godot

    - name: â¬‡ï¸ Download Editor
      if: steps.cache_editor.outputs.cache-hit != 'true'
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/download_editor.sh"
        "${{ github.action_path }}/scripts/download_editor.sh" "${{ steps.read_version.outputs.version }}" "${{ runner.os }}"

    - name: ðŸ’¾ Save Cache Editor
      if: steps.cache_editor.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cache_editor.outputs.cache-primary-key }}
        path: ~/.godot

    - name: âš™ï¸ Install Editor
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/install_editor.sh"
        executable_file=$("${{ github.action_path }}/scripts/install_editor.sh" "${{ steps.read_version.outputs.version }}" "${{ runner.os }}")
        echo GODOT="$executable_file" >> "$GITHUB_ENV"
