name: Godot Pack
description: Packages and uploads the Godot addon artifact.

inputs:
  addon:
    description: Path to the Godot addon, relative to the repository root.
    required: true
  version:
    description: Version number to apply to the package.
    required: true
  name:
    description: Desired name for the uploaded Godot addon artifact.
    required: true
  duration:
    description: Retention duration (in days) for the uploaded artifact. A value of 0 uses the default retention period.
    required: false
    default: "1"

runs:
  using: composite
  steps:
    - name: 🚚 Copy Godot Addon
      shell: bash
      run: |
        ARTIFACT="./artifacts/${{ inputs.name }}"
        mkdir -p $ARTIFACT
        cp -r ${{ inputs.addon }} $ARTIFACT

    - name: 📦 Pack Godot Addon
      shell: bash
      run: |
        ADDON="./artifacts/${{ inputs.name }}/$(basename ${{ inputs.addon }})"
        cp README.md LICENSE $ADDON
        sed -i 's/version="[^"]*"/version="'${{ inputs.version }}'"/' $ADDON/plugin.cfg
        cd ./artifacts && zip -r ${{ inputs.name }}.zip ${{ inputs.name }}

    - name: 📤 Upload Addon Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ./artifacts/${{ inputs.name }}.zip
        retention-days: ${{ inputs.duration }}
