name: Test Unity
description: Run EditMode and PlayMode tests for a Unity project.

inputs:
    project:
        description: Path to the Unity project folder
        required: true

runs:
    using: composite
    steps:
        - name: 🧪 Test Project
          shell: bash
          env:
              PROJECT_DIR: ${{ inputs.project }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/test_project.sh"
              "${{ github.action_path }}/scripts/test_project.sh"
