name: Build .NET
description: Build a .NET project.

inputs:
    project:
        description: The relative path to .NET project directory containing the csproj file.
        required: true
    configuration:
        description: The build configuration such as Release or Debug.
        required: true
    version:
        description: The version number to set for the build.
        required: false
    define-symbols:
        description: Optional symbols to define during the build.
        required: false

runs:
    using: composite
    steps:
        - name: 🏗️ Build Project
          shell: bash
          env:
              PROJECT_DIR: ${{ inputs.project }}
              CONFIGURATION: ${{ inputs.configuration }}
              VERSION: ${{ inputs.version }}
              DEFINE_SYMBOLS: ${{ inputs.define-symbols }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/build_project.sh"
              "${{ github.action_path }}/scripts/build_project.sh"
