name: Pack .NET
description: Package a .NET project into a NuGet package

inputs:
    project:
        description: Path to .NET project directory containing the csproj file
        required: true
    configuration:
        description: Build configuration (Release or Debug)
        required: true
        default: "Release"
    version:
        description: Version number to apply to the package
        required: true
    name:
        description: Name of the output package file (without .nupkg extension)
        required: true
    directory-build-props:
        description: Path to Directory.Build.props file to update version (optional)
        required: false
        default: ""

outputs:
    package:
        description: Path to the created NuGet package file
        value: ${{ steps.pack.outputs.package }}
    modified-files:
        description: Newline-separated paths to modified files in workspace (csproj, Directory.Build.props)
        value: ${{ steps.pack.outputs.modified-files }}

runs:
    using: composite
    steps:
        - name: 📦 Pack Project
          id: pack
          shell: bash
          env:
              PROJECT_PATH: ${{ inputs.project }}
              BUILD_CONFIGURATION: ${{ inputs.configuration }}
              PACKAGE_VERSION: ${{ inputs.version }}
              PACKAGE_NAME: ${{ inputs.name }}
              DIRECTORY_BUILD_PROPS: ${{ inputs.directory-build-props }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/pack_project.sh"
              "${{ github.action_path }}/scripts/pack_project.sh"
