name: Release Github
description: Creates a GitHub release and uploads specified artifacts.

inputs:
  title:
    description: The title for the GitHub release.
    required: true
  version:
    description: The version number for the release.
    required: true
  github-token:
    description: The GitHub token for authentication.
    required: true

runs:
  using: composite
  steps:
    - name: 📥 Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
        merge-multiple: true

    - name: 🔖 Create Tag and Push
      shell: bash
      run: |
        git config user.name GitHub Actions
        git config user.email actions@github.com
        git tag ${{ inputs.version }}
        git push origin ${{ inputs.version }}

    - name: 📝 Create GitHub Release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        files=$(find ./artifacts -type f | xargs)

        if [[ ${{ inputs.version }} != 0.0.0 ]]; then
          gh release create ${{ inputs.version }} $files \
            --title "${{ inputs.title }}" --generate-notes --notes-start-tag ${{ inputs.version }}
        else
          gh release create ${{ inputs.version }} $files \
            --title "${{ inputs.title }}"
        fi
