name: Upload Artifact
description: Upload build artifacts with path metadata for restoration support.

inputs:
    name:
        description: Artifact name.
        required: false
        default: "artifact"
    path:
        description: A file, directory or wildcard pattern that describes what to upload.
        required: true
    if-no-files-found:
        description: |
            What to do if no files are found that match the path.
            Options: ignore, warn, error.
        required: false
        default: "warn"
    retention-days:
        description: Number of days to retain artifact (1-90).
        required: false
        default: "0"
    compression-level:
        description: Level of compression to apply to the artifact (0-9).
        required: false
        default: "6"
    overwrite:
        description: Whether to overwrite an existing artifact with the same name.
        required: false
        default: "false"
    include-hidden-files:
        description: Whether to include hidden files (dotfiles) in the artifact.
        required: false
        default: "false"

runs:
    using: composite
    steps:
        - name: 📦 Prepare Artifact
          id: prepare
          shell: bash
          env:
              ARTIFACT_NAME: ${{ inputs.name }}
              ARTIFACT_PATH: ${{ inputs.path }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/upload_artifact.sh"
              "${{ github.action_path }}/scripts/upload_artifact.sh"

        - name: 📤 Upload Artifact
          uses: actions/upload-artifact@v4
          with:
              name: ${{ inputs.name }}
              path: ${{ steps.prepare.outputs.staging-dir }}
              if-no-files-found: ${{ inputs.if-no-files-found }}
              retention-days: ${{ inputs.retention-days }}
              compression-level: ${{ inputs.compression-level }}
              overwrite: ${{ inputs.overwrite }}
              include-hidden-files: ${{ inputs.include-hidden-files }}
