name: Upload Artifact
description: Upload build artifacts with path metadata for restoration support.

inputs:
    name:
        description: Artifact name.
        required: true
    path:
        description: |
            A file, directory or wildcard pattern that describes what to upload.
            Supports multiple paths (one per line) and glob patterns.
        required: true
    retention-days:
        description: Number of days to retain artifact (1-90).
        required: false
        default: "30"

runs:
    using: composite
    steps:
        - name: 📦 Prepare Artifact
          id: prepare
          shell: bash
          env:
              ARTIFACT_NAME: ${{ inputs.name }}
              ARTIFACT_PATH: ${{ inputs.path }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/upload_artifact.sh"
              "${{ github.action_path }}/scripts/upload_artifact.sh"

        - name: 📤 Upload Artifact
          uses: actions/upload-artifact@v4
          with:
              name: ${{ inputs.name }}
              path: ${{ steps.prepare.outputs.staging-dir }}
              retention-days: ${{ inputs.retention-days }}
