name: Publish to Github
description: Creates a GitHub release and uploads specified artifacts.

inputs:
  title:
    description: The title for the GitHub release.
    required: true
  version:
    description: The version number for the release.
    required: true
  changelog:
    description: The latest version number for the release.
    required: true
  github-token:
    description: The GitHub token for authentication.
    required: true
  assets-folder:
    description: The folder path containing assets to include in the release.
    required: false

runs:
  using: composite
  steps:
    - name: 🔖 Create Tag and Push
      shell: bash
      run: |
        git config user.name GitHub Actions
        git config user.email actions@github.com
        git tag ${{ inputs.version }}
        git push origin ${{ inputs.version }}

    - name: 📝 Create GitHub Release
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        assets=$(find ${{ inputs.assets-folder }} -type f | xargs)
        gh release create ${{ inputs.version }} $assets --title "${{ inputs.title }}" --notes "${{ inputs.changelog }}"
