name: Publish to Github
description: Creates a GitHub release and uploads specified artifacts.

inputs:
    title:
        description: The title for the GitHub release.
        required: true
    version:
        description: The version number for the release.
        required: true
    changelog:
        description: The changelog for the release.
        required: true
    github-token:
        description: The GitHub token for authentication.
        required: true
    assets:
        description: The assets to include in the release.
        required: false
        default: ""

runs:
    using: composite
    steps:
        - name: 🔖 Configure Git
          shell: bash
          run: |
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"

        - name: 📝 Create GitHub Release
          shell: bash
          env:
              GH_TOKEN: ${{ inputs.github-token }}
              RELEASE_VERSION: ${{ inputs.version }}
              RELEASE_TITLE: ${{ inputs.title }}
              RELEASE_NOTES: ${{ inputs.changelog }}
              RELEASE_ASSETS: ${{ inputs.assets }}
          run: |
              NOTES_FILE=$(mktemp)
              printf '%s' "$RELEASE_NOTES" > "$NOTES_FILE"

              if [[ -n "$RELEASE_ASSETS" ]]; then
                IFS=' ' read -ra assets <<< "$RELEASE_ASSETS"
                gh release create "$RELEASE_VERSION" "${assets[@]}" \
                  --title "$RELEASE_TITLE" \
                  --notes-file "$NOTES_FILE"
              else
                gh release create "$RELEASE_VERSION" \
                  --title "$RELEASE_TITLE" \
                  --notes-file "$NOTES_FILE"
              fi

              rm -f "$NOTES_FILE"
