name: Publish to GitHub
description: Create a GitHub release and upload specified artifacts.

inputs:
    title:
        description: The title for the GitHub release
        required: true
    version:
        description: The version number for the release
        required: true
    changelog:
        description: The changelog content for the release
        required: true
    github-token:
        description: The GitHub token for authentication
        required: true
    assets:
        description: Space-separated list of asset paths to include in the release
        required: false
        default: ""

runs:
    using: composite
    steps:
        - name: 🔖 Configure Git
          shell: bash
          run: |
              git config user.name "github-actions[bot]"
              git config user.email "github-actions[bot]@users.noreply.github.com"

        - name: 📝 Create GitHub Release
          shell: bash
          env:
              GH_TOKEN: ${{ inputs.github-token }}
              RELEASE_VERSION: ${{ inputs.version }}
              RELEASE_TITLE: ${{ inputs.title }}
              RELEASE_NOTES: ${{ inputs.changelog }}
              RELEASE_ASSETS: ${{ inputs.assets }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/create_release.sh"
              "${{ github.action_path }}/scripts/create_release.sh"
