name: Setup Xcode
description: Validate and select the appropriate Xcode version with iOS SDK compatibility.

inputs:
    xcode-version:
        description: Target Xcode version such as 16.0
        required: true

runs:
    using: composite
    steps:
        - name: 🎯 Select Xcode
          id: select-xcode
          shell: bash
          env:
              XCODE_VERSION: ${{ inputs.xcode-version }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/select_xcode.sh"
              "${{ github.action_path }}/scripts/select_xcode.sh"

        - name: 📥 Install Platforms
          shell: bash
          run: |
              chmod +x "${{ github.action_path }}/scripts/install_platforms.sh"
              "${{ github.action_path }}/scripts/install_platforms.sh"
