name: Publish to Firebase
description: Upload a build file to Firebase App Distribution for testing.

inputs:
    file:
        description: Path to the build file to be uploaded to Firebase App Distribution
        required: true
    app-id:
        description: The Firebase App ID associated with the app
        required: true
    credentials:
        description: The Firebase credentials as base64 used for authentication
        required: true
    release-notes:
        description: Release notes to be displayed to testers in Firebase App Distribution
        required: false
        default: ""
    tester-groups:
        description: Comma-separated list of tester groups to distribute the build to
        required: false
        default: ""

runs:
    using: composite
    steps:
        - name: 🔧 Install Firebase CLI
          shell: bash
          run: curl -sL https://firebase.tools | bash

        - name: 🚀 Distribute to Firebase
          shell: bash
          env:
              FILE: ${{ inputs.file }}
              APP_ID: ${{ inputs.app-id }}
              CREDENTIALS: ${{ inputs.credentials }}
              RELEASE_NOTES: ${{ inputs.release-notes }}
              TESTER_GROUPS: ${{ inputs.tester-groups }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/distribute_file.sh"
              "${{ github.action_path }}/scripts/distribute_file.sh"
