name: Publish to Firebase
description: Uploads a build file to Firebase App Distribution.

inputs:
  file:
    description: The name of the build file to be uploaded to Firebase App Distribution.
    required: true
  app-id:
    description: The Firebase App ID associated with the app.
    required: true
  credentials:
    description: The Firebase credentials as base64 used for authentication.
    required: true
  release-notes:
    description: Notes for this release to be displayed to testers in Firebase App Distribution.
    required: false
  tester-groups:
    description: A comma-separated list of tester groups to distribute the build to.
    required: false

runs:
  using: composite
  steps:
    - name: 🚀 Install Firebase
      shell: bash
      run: curl -sL https://firebase.tools | bash

    - name: 🚀 Distribute to Firebase
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/distribute_file.sh"
        "${{ github.action_path }}/scripts/distribute_file.sh" \
        "${{ inputs.file }}" \
        "${{ inputs.app-id }}" \
        "${{ inputs.credentials }}" \
        "${{ inputs.release-notes }}" \
        "${{ inputs.tester-groups }}"
