name: Test .NET
description: Tests a .NET project.

inputs:
  project:
    description: The relative path to the .NET test project (.csproj) file.
    required: true

runs:
  using: composite
  steps:
    - name: 🛠️ Setup .NET SDK
      uses: actions/setup-dotnet@v4
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_NOLOGO: true
      with:
        global-json-file: ${{ inputs.global-json-file }}

    - name: ♻️ Restore Project
      shell: bash
      run: dotnet restore ${{ inputs.project }}

    - name: ⚙️ Build Project
      shell: bash
      run: dotnet build --no-restore ${{ inputs.project }}

    - name: 🧪 Test Project
      shell: bash
      run: dotnet test --no-build --no-restore ${{ inputs.project }}
