name: Test .NET
description: Tests a .NET project.

inputs:
  project:
    description: The relative path to .NET project directory containing the `csproj` file.
    required: true
  configuration:
    description: The build configuration (e.g., Release or Debug).
    required: true

runs:
  using: composite
  steps:
    - name: 🧪 Test Project
      shell: bash
      run: |
        chmod +x "${{ github.action_path }}/scripts/test_project.sh"
        "${{ github.action_path }}/scripts/test_project.sh" "${{ inputs.project }}" "${{ inputs.configuration }}"
