name: Test .NET
description: Run tests for a .NET project with specified configuration.

inputs:
    project:
        description: Path to .NET project directory containing the csproj file
        required: true
    configuration:
        description: Build configuration such as Release or Debug
        required: true

runs:
    using: composite
    steps:
        - name: 🧪 Test Project
          shell: bash
          env:
              PROJECT_PATH: ${{ inputs.project }}
              BUILD_CONFIGURATION: ${{ inputs.configuration }}
          run: |
              chmod +x "${{ github.action_path }}/scripts/test_project.sh"
              "${{ github.action_path }}/scripts/test_project.sh"
