name: Godot Pack

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      name:
        required: true
        type: string
      id:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ARTIFACT_DIR: ./artifacts

    steps:
      - name: 🔄 Checkout Code
        uses: actions/checkout@v4

      - name: 🔗 Set Variables
        run: |
          ARTIFACT_NAME="${{ inputs.name }}-${{ inputs.version }}-godot-addon"
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
          echo "ARTIFACT=$ARTIFACT_DIR/$ARTIFACT_NAME" >> $GITHUB_ENV

      - name: 📦 Pack Godot Addon
        run: |
          mkdir -p $ARTIFACT
          cp -r ${{ inputs.path }}/* $ARTIFACT
          cp README.md LICENSE $ARTIFACT/${{ inputs.id }}
          sed -i 's/version="[^"]*"/version="'${{ inputs.version }}'"/' $ARTIFACT/${{ inputs.id }}/plugin.cfg

      - name: 🗜️ Zip Godot Addon
        run: |
          cd $ARTIFACT_DIR && zip -r $ARTIFACT_NAME.zip $ARTIFACT_NAME

      - name: 📤 Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godot-addon
          path: $ARTIFACT.zip
