name: Godot Pack

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      id:
        required: true
        type: string
      version:
        required: true
        type: string
      name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ARTIFACT_DIR: ./artifacts/package/release

    steps:
      - name: 📦 Pack Godot Addon
        run: |
          mkdir -p $ARTIFACT_DIR/${{ inputs.name }}
          cp -r ${{ inputs.path }} $ARTIFACT_DIR/${{ inputs.name }}
          cp README.md LICENSE $ARTIFACT_DIR/${{ inputs.name }}/${{ inputs.id }}
          sed -i 's/version="[^"]*"/version="'${{ inputs.version }}'"/' $ARTIFACT_DIR/${{ inputs.name }}/${{ inputs.id }}/plugin.cfg

      - name: 🗜️ Zip Godot Addon
        run: |
          cd $ARTIFACT_DIR && zip -r ${{ inputs.name }}.zip ${{ inputs.name }}

      - name: 📤 Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: godot-addon
          path: $ARTIFACT_DIR/${{ inputs.name }}.zip
