name: Nuget Release

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      id:
        required: true
        type: string
      version:
        required: true
        type: string
      platform:
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ARTIFACT_DIR: ./artifacts

    steps:
      - name: 🔗 Set Variables
        run: |
          echo "ARTIFACT_NAME=${{ inputs.name }}-${{ inputs.version }}${{ format('-{0}', inputs.platform) || '' }}" >> $GITHUB_ENV
          echo "ARTIFACT=$ARTIFACT_DIR/$ARTIFACT_NAME.nupkg" >> $GITHUB_ENV

      - name: 📥 Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: nuget-package${{ format('-{0}', inputs.platform) || '' }}
          path: $ARTIFACT

      - name: 🚀 Publish NuGet Package
        run: dotnet nuget push $ARTIFACT --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate --source https://api.nuget.org/v3/index.json
