name: Manual Test Unity Setup

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: "Test type to run"
        required: true
        default: "basic"
        type: choice
        options:
          - basic
          - with-modules
          - all-platforms
          - cache-test

jobs:
  test-basic:
    if: ${{ github.event.inputs.test_type == 'basic' || github.event.inputs.test_type == 'all-platforms' }}
    name: Basic Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Test Unity Setup
        uses: ./.github/actions/setup-unity
        with:
          project-path: sandbox/UnityApplication

      - name: Verify
        run: |
          echo "✅ Unity Version: $UNITY_VERSION"
          echo "✅ Unity Path: $UNITY_PATH"
          unity -version || echo "Unity command not in PATH"

  test-with-modules:
    if: ${{ github.event.inputs.test_type == 'with-modules' }}
    name: Test with Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Test Unity Setup with Modules
        uses: ./.github/actions/setup-unity
        with:
          unity-version: "6.0.0f1"
          unity-modules: "android,webgl"

      - name: Verify Modules
        run: |
          echo "Testing Android build support..."
          unity -batchmode -quit -logFile - -buildTarget Android || echo "Android module check"

  test-all-platforms:
    if: ${{ github.event.inputs.test_type == 'all-platforms' }}
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Test Unity Setup
        uses: ./.github/actions/setup-unity
        with:
          unity-version: "6.0.0f1"

      - name: Verify on ${{ matrix.os }}
        shell: bash
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Unity Version: $UNITY_VERSION"
          echo "Unity Path: $UNITY_PATH"

  test-cache:
    if: ${{ github.event.inputs.test_type == 'cache-test' }}
    name: Test Caching
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: First Install (No Cache)
        uses: ./.github/actions/setup-unity
        with:
          unity-version: "6.0.0f1"
          cache: "true"

      - name: Clear Unity
        run: |
          sudo rm -rf ~/Unity/Hub/Editor/6.0.0f1 || true

      - name: Second Install (Should Use Cache)
        uses: ./.github/actions/setup-unity
        with:
          unity-version: "6.0.0f1"
          cache: "true"
