name: Test Unity Setup Action
on:
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test-basic-setup:
    name: Test Basic Setup (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Test Unity Setup (Auto-detect)
        uses: ./.github/actions/setup-unity
        with:
          project-path: "sandbox/UnityApplication"
      - name: Verify Unity Installation
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then unity -version; else Unity -version; fi

  test-with-modules:
    name: Test Module Installation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Unity Setup with Modules
        uses: ./.github/actions/setup-unity
        with:
          unity-version: "6000.1.9f1 (ed7b183fd33d)"
          unity-modules: "webgl, android"
      - name: Check Modules
        run: |
          Unity -batchmode -quit -logFile - -buildTarget WebGL
          Unity -batchmode -quit -logFile - -buildTarget Android

  prime-cache:
    name: Test Caching (1/2 - Prime Cache)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Save to Cache
        uses: ./.github/actions/setup-unity
        with:
          unity-version: "6000.1.9f1 (ed7b183fd33d)"
          cache: "true"

  use-cache:
    name: Test Caching (2/2 - Use Cache)
    runs-on: windows-latest
    needs: prime-cache
    steps:
      - uses: actions/checkout@v4
      - name: Second Install (Should be a cache-hit)
        id: use_cache_step
        uses: ./.github/actions/setup-unity
        with:
          unity-version: "6000.1.9f1 (ed7b183fd33d)"
          cache: "true"
      - name: Verify Cache was Used
        if: steps.use_cache_step.outputs.download-cache-hit != 'true'
        run: |
          echo "::error::The download cache was not used on the second run."
          exit 1
      - name: Verify Unity Installation from Cache
        run: unity -version

  test-no-cache:
    name: Test Without Cache
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Unity Setup without Cache
        uses: ./.github/actions/setup-unity
        with:
          unity-version: "6000.1.9f1 (ed7b183fd33d)"
          cache: "false"
      - name: Verify Unity Installation
        run: Unity -version

  test-error-handling:
    name: Test Error Handling
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Invalid Version (Should Fail)
        id: test_invalid
        continue-on-error: true
        uses: ./.github/actions/setup-unity
        with:
          unity-version: "invalid"
      - name: Verify Invalid Version Failed
        if: steps.test_invalid.outcome == 'success'
        run: |
          echo "::error::Action should have failed with invalid version."
          exit 1