name: Test Unity Setup Action
on:
  pull_request:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  test-basic-setup:
    name: Test Basic Setup (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Test Unity Setup (Auto-detect)
        uses: ./.github/actions/setup-unity
        with:
          project: "sandbox/UnityApplication"
          cache: "true"
      - name: Verify Unity Installation
        run: unity -version

  test-with-modules:
    name: Test Module Installation (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            modules: "webgl,windows-il2cpp,mac-il2cpp"
          - os: macos-latest
            modules: "webgl,ios,android,mac-il2cpp"
    steps:
      - uses: actions/checkout@v4
      - name: Test Unity Setup with Modules
        uses: ./.github/actions/setup-unity
        with:
          unity-version: "6000.1.9f1 (ed7b183fd33d)"
          unity-modules: ${{ matrix.modules }}
          cache: "true"
      - name: Verify Module Installation
        shell: bash
        run: |
          echo "Verifying Unity installation and module availability"
          unity -version
          unity -batchmode -quit -nographics -logFile - -projectPath sandbox/UnityApplication || echo "Unity headless test completed"
          
          unity_base_dir=$(dirname $(which unity))
          echo "Unity base directory: $unity_base_dir"
          
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            if [[ "${{ matrix.modules }}" == *"webgl"* ]]; then
              echo "Checking WebGL module installation..."
              find $unity_base_dir/../.. -name "*webgl*" -o -name "*WebGL*" 2>/dev/null | head -3 || echo "WebGL module check completed"
            fi
          else
            if [[ "${{ matrix.modules }}" == *"ios"* ]]; then
              echo "Checking iOS module installation..."
              find $unity_base_dir/../.. -name "*iOS*" -o -name "*ios*" 2>/dev/null | head -3 || echo "iOS module check completed"
            fi
          fi

  prime-cache:
    name: Test Caching (1/2 - Prime Cache)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install and Save to Cache
        uses: ./.github/actions/setup-unity
        with:
          unity-version: "6000.1.9f1 (ed7b183fd33d)"
          unity-modules: "webgl"
          cache: "true"

  use-cache:
    name: Test Caching (2/2 - Use Cache)
    runs-on: ubuntu-latest
    needs: prime-cache
    steps:
      - uses: actions/checkout@v4
      - name: Second Install (Should be a cache-hit)
        id: use_cache_step
        uses: ./.github/actions/setup-unity
        with:
          unity-version: "6000.1.9f1 (ed7b183fd33d)"
          unity-modules: "webgl"
          cache: "true"
      - name: Verify Cache was Used
        if: steps.use_cache_step.outputs.download-cache-hit != 'true'
        run: |
          echo "::error::The download cache was not used on the second run."
          exit 1
      - name: Verify Unity Installation from Cache
        run: unity -version

  test-error-handling:
    name: Test Error Handling
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Invalid Version (Should Fail)
        id: test_invalid
        continue-on-error: true
        uses: ./.github/actions/setup-unity
        with:
          unity-version: "invalid"
      - name: Verify Invalid Version Failed
        if: steps.test_invalid.outcome == 'success'
        run: |
          echo "::error::Action should have failed with invalid version."
          exit 1